---
title: "Reproduserbarhet i sammenheng med storedata"
output: html_notebook
---

## <span style="color:pink"> *Introduksjon*

I denne oppgaven tar vi for oss viktigheten av reproduserbarhet når man arbeider med store data.Vi vil se på hva *R* og *R-studio* er, og hvordan dette kan hjelpe oss med reproduserbarhet og replikerbarhet. Vi vil også forklare hva *R-markdown* og *R-Notebook* er.  

## <span style="color:lightblue">*Reproduserbarhet og replikerbarhet*
### **Hvorfor bryr vi oss om reproduserbarhet og replikerbarhet?**
Forskere prøver ofte å reprodusere eksprimenter for å øke troverdigheten til forsøket og resultatene i eksprimentet. Hvis eksprimentet kan reproduseres og få de samme svarene øker tiltroen/tillten til resultatet.Reproduserbarhet går ut på å bruke de samme dataene som allerede er brukt i forsåket, utføre da samme analysene, og ende opp med de samme svarene.

Replikerbarhet blir sett på som "gull" standarden innenfor forskning. Replikerbarhet går ut på at det skal være mulig å gjøre forsøket på nytt, med nye data, og ende opp med samme svar. Reproduserbarhet er nødvendig for å få replikerbarhet, men ikke tilstrekkelig nok til å gi replikerbarhet.

Reproduserbarhet og replikerbarhet har vist seg og ikke være noen selvfølge innen forskning. Det er flere meninger og tanker rundt dette. Noen hevder forskningen burde være reproduserbar for at den skal kunne publiseres. Andre går så lang og mener den også bør kunne replikeres.Vi vil ikke gå nærmere inn på dette, men vi vil se mer på grunnene til at studier ikke er reproduserbare og replikerbare, og ulike løsninger på dette senere i oppgaven. 

### **Hvorfor R og R studio?**
Både R og R studio er åpen kildekode programvarer og er gratis. Det brukes i sammenheng med forskning og datavisualisering. R er ett kodespråk for statistisk databehandling og grafikk, mens R-studio er ett integrert utviklingsmiljø for R. R og R studio gjør sammarbeid enklere via feks. Git og Github. Man kan importere og manipulere data og kjøre dette i ett maskinlæringsprogram via R studio. Skal man kjøre linerar regrisjon eller lignende kan man bruke R og R studio. Analyser gjort i R og R studio er reproduserbare, da alt som er gjort ligger inne i "history" og kan bli hentet frem igjen.  

### **R-markdown og R-notebooks**
R-Markdown gjør det mulig å skape rike, fullt dokumenterete, reproduserbare analyser (kilde). R koder, kommentarer, metadata ligger da inni det samme dokumentet. Dette gjør at man i etterkant kan se hvilke data som har blitt brukt. Hvilke formler som er brukt for å få svarene i analysen. Alt som har blitt gjort i analysen kan bli funnet igjen. Det er ikke gjort analyser separert hvor svarene har blitt plottet inn i dokumentet i etterkant.Dette dokumentet er skrevet med R notebook, som er et r-markdown dokument med kode "chunks" som kan utføres uavhengig og interaktivt, hvor resultatet er synlig med en gang. Dokumentet blir en blanding av vanlig skrift og koder, noe som gjør det svært effektivt iforhold til andre skriveprogrammer. Kodene som brukes er ikke synlige i det endelige resultatet som blir publisert, kun resultatene av disse kodene. Ønsker man derrimot å se hvilke koder som er blitt brukt er det mulig i etterkant. Dette gjør at dokumentet blir reproduserbart.

## *Hvorfor er ikke flere studier reproduserbare og replikerbare?*

Det kan være ulike grunner til at studier ikke er reproduserbare og/eller replikerbare. En årsak kan være feilaktig forkastning av null hypotesen. Dette kan være resultat av feil i analysen eller ett dårlig utvalg. Det kan også være ett resultat av feilaktig innplotting som har gått uanmerket. Når analysen blir gjort på ny igjen vil resultatet bli annerledes. Innen psykologifaget ble det gjort en undersøkelse hvor de prøvde å replikere 100 undersøkelser fra de siste 3 årene som var blitt publisert i de tre mest respekterte journalene innenfor faget. De fant ut att effektene fra funnene i disse studiene ble halvert etter at de ble gjennomført på ny (replikert).De fant også at i <span style="color:red"> 95% </span> av de orginale undersøkelsen hadde de fått ett signifikans nivå på 0,05 eller under, mens etter at undersøkelsen ble utført på ny var det kun <span style="color:red"> 36% </span> som hadde ett signifikant resultat.

### **Problemet med excell og dagens løsninger**
Dagens bruk av systemer som excel kan gjøre arbeidet med store data sett vansklig og uoversiktlig. Små feil gjort innefor en av "cellene" kan fort oversees, samt føre til at resultatet endres uten at det merkes. Når slike feil blir gjort er de vanskelige å identifisere hvis det er mange data. Prøver man å reprodusere studien ender man opp med ett annet svar en den orginale studien uten å finne årsaken til feilen. 

### **wale of London**
Historien om JP Morgan Chase tabben som kostet selskapet 2 Milliarder dollar, aksjeinvestorer som jobbet for JP Morgan hadde slått inn en feil i excel spreadsheet, som underestimerte feilen i den syntetiske modellen de investoren brukte for å kalkulere risikoen i handelen. Videre undersøkelser viste hvordan tabben en enkel tabbe i excel spreadsheet remodelerte den finansielle risikomodellen som ble brukt i sammenheng med investeringen.

## *Historisk data arkivering*

## *Løser R notebooks problemet med reproduserbarhet?*

## *Code chunks og text chunks*

## *Reproduserbarhet i ulike sektorer*


## *Konklusjon*

# ***Litteraturliste***




